# -*- coding: utf-8 -*-
"""Pertemuan 7, exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Djm1FP31ds5P4dmrb4F7gUiD8C1RC-R
"""

#exercise1

name = input("Input name: ")
age = input("Input age: ")
address = input("Input address: ")
email = input("Input email: ")


file = open("Biodata.txt", "w")
file.write("Name: "+ name + "\n")
file.write("Age: "+ age + "\n")
file.write("Address: "+ address + "\n")
file.write("Email: "+ email + "\n")
file.close()

file = open("Biodata.txt", "r")
text = file.read()
print(text)
file.close()

#exercise2

def buat_file():
    nama_file = input("Masukkan Nama File: ")
    nama = input("Masukkan Namamu: ")
    nim = input("Masukkan NIM kamu: ")
    angkatan = input("Masukkan tahun angkatanmu: ")

    with open(nama_file + ".txt", "w") as file:
        file.write("Nama: " + nama + "\n")
        file.write("NIM: " + nim + "\n")
        file.write("Angkatan: " + angkatan + "\n")

    print("File Berhasil Dibuat")


def baca_file():
    nama_file = input("Masukkan Nama File: ")

    with open(nama_file + ".txt", "r") as file:
        data = file.read()

    print(data)


def tambah_file():
    nama_file = input("Masukkan Nama File: ")
    nama_sahabat = input("Masukkan Nama Sahabatmu: ")
    catatan = input("Masukkan Catatan Tambahan kamu: ")

    with open(nama_file + ".txt", "a") as file:
        file.write("Nama Sahabat: " + nama_sahabat + "\n")
        file.write("Catatan: " + catatan + "\n")

    print("Data Berhasil Ditambahkan")


while True:
    print("\n===== Program File Handling =====")
    print("1. Membuat dan Menulis File")
    print("2. Membaca File")
    print("3. Menambahkan Text Pada File")
    print("4. Keluar Dari Program")

    pilihan = input("Masukkan Pilihan Berupa Angka (1/2/3/4): ")

    if pilihan == "1":
        buat_file()

    elif pilihan == "2":
        baca_file()

    elif pilihan == "3":
        tambah_file()

    elif pilihan == "4":
        print("Terima Kasih Sudah Menggunakan Program Saya")
        break

    else:
        print("Pilihan tidak tersedia!")

#exercise4

import pandas as pd

# Membaca file CSV
df = pd.read_csv("Negara.csv")

# Menampilkan data
print("Bentuk Data Table:")
print(df)

# Menghitung Mean
mean = df["Population"].mean()

# Menghitung Standard Deviation
std = df["Population"].std()

print("\nMean:", mean)
print("Standard Deviation:", std)

#maaf baru mengumpulkan sekarang kak,karna dari kemarin2 saya benar2 sibuk disekolah sampai rumah,akibat kegiatan kotemporer yang adalah program sekolah mengharuskan saya dengan teman kelompok saya bekerja terus terusan.maaf kak untuk sebelumnya